### ISSUE TITLE
Latest version of apollo-upload-client cannot support ie 11 due to no es5 module

### ISSUE THREAD

**Issue by Leruiz** [jaydenseric/apollo-upload-client#124]
```apollo-upload-client@9.0.0``` only provides ```es6``` module in ```src/index.js```, which cannot run in ie 11. Now the only solution is to use ```v8.1.0``` instead of ```v9.0.0```.

So when could the ```es5``` module be provided, please?

**Comment by jaydenseric** [comment]
What specifically can't run in IE11? What is the error?

**Comment by jaydenseric** [comment]
I don't see any `import` or `export` ESM syntax in there (as expected, the ESM file ends in `.mjs`, not `.js`). Is it the `const` that you're referring to? That syntax is fine in IE11: https://caniuse.com/#feat=const.

**Comment by Leruiz** [comment]
The ```const``` seems to have nothing with this problem. I replace all ```const ``` with ```var```. But the error stills exists.

**Comment by jaydenseric** [comment]
This is really not enough to go on, sorry. I'm not in a good position to debug your code for you by looking at screenshots of minified code. If you can isolate a _specific_ thing that is wrong with `apollo-upload-client`, along with minimal reproduction steps we can reopen the issue!

**Comment by Leruiz** [comment]
I have built a minimal project to reproduce the problem. Here is the [github url ](https://github.com/Leruiz/apollo-upload-client-minal-project.git). 

When I open the web in chrome, the normal page is 
![1](https://user-images.githubusercontent.com/20510533/47782633-aa040800-dd3b-11e8-9b2c-a69840f60b6d.png)

But in ie 11, the page cannot be displayed and an error 'SCRIPT1010' appears in console.
![2](https://user-images.githubusercontent.com/20510533/47782791-06672780-dd3c-11e8-9164-eb0d5fe78efc.png)

**Comment by jaydenseric** [comment]
You have gone to more effort, so thanks for that.

But what is the problem with `apollo-upload-client`? Which lines are "wrong" in the published file you can see here: https://unpkg.com/apollo-upload-client@9.0.0/lib/index.js

I don't know Vue, and all there are a lot of files and folders in that repo. Why do you need Vue to show me the problem? Why not just one JS file with an Apollo Client instance making a request?

Also, I work on a Mac so it is a lot of trouble for me to setup your repo, then start debugging IE11 using Browserstack or something. What if I go to 30min of effort, and discover it was not an `apollo-upload-client` bug?

**Comment by jaydenseric** [comment]
Running `yarn dev` in the `backend` project results in this error:

<img width="558" alt="screen shot 2018-10-31 at 10 03 58 pm" src="https://user-images.githubusercontent.com/1754873/47784232-16413480-dd59-11e8-84fb-6c154178870f.png">

**Comment by jaydenseric** [comment]
You can always query a public GraphQL API like https://github.com/lucasbento/graphql-pokemon so you don't have to set one up yourself.

**Comment by Leruiz** [comment]
I am sorry for a complicated front end project. The main related file is ```front-end/pages/index.vue```. In the ie 11 browser, the page cannot be rendered at all due to the part of code from  ```index.js``` of ```apollo-upload-client``` in ```.nuxt``` cannot be recognized by the browser. I also tried to transform the ```index.js``` to ``es5``` by babel, and everything goes well. So I guess that the provided file cannot be used in ```ie 11``` .

**Comment by jaydenseric** [comment]
Which line, and what syntax, in `apollo-upload-client` causes the problem?

**Comment by Leruiz** [comment]
Now, according to the message from ie console, The error can only be tracked at the beginning of the ```index.js```.

**Comment by jaydenseric** [comment]
I don't think it has to do with the level of ES syntax published. I tried explicitly setting browserslist to `> 1%, IE 11` for `@babel/preset-env` and it made no difference to the output. Babel thinks the code is ok for IE 11. It must be something else to do with your environment, bundling, minification, or polyfills.

Your IE 11 might not be running in "edge" mode: http://superdavid.me/ie/front-end/2018/01/17/expected-identifier-error.html

Try adding this to the page `<head>`:

```html
<meta http-equiv="x-ua-compatible" content="IE=edge" />
```

**Comment by Leruiz** [comment]
I tried to add the ```meta``` but has no effect. 
But I tried to modify the code and found some problems.

At the first,  the error message shows as below
![1](https://user-images.githubusercontent.com/20510533/47788089-b09a7b80-dd4b-11e8-855a-c4c1459cadfc.png)

Click into the file name, the cursor points to  the first line
`const { ApolloLink, Observable } = require('apollo-link')`

![2](https://user-images.githubusercontent.com/20510533/47788136-d0ca3a80-dd4b-11e8-80ef-cb478f341beb.png)

Then I change this line as below
```
// const { ApolloLink, Observable } = require('apollo-link')
const _apolloLink = require('apollo-link')
const ApolloLink = _apolloLink.ApolloLink
const Observable = _apolloLink.Observable
```

The error message is the same but the cursor positions are different, as below
![3](https://user-images.githubusercontent.com/20510533/47788343-6b2a7e00-dd4c-11e8-9ec8-e88f4e7e122c.png)

Similarly, I rewrite the part of code as below, 

```
// const {
//   selectURI,
//   selectHttpOptionsAndBody,
//   fallbackHttpConfig,
//   serializeFetchParameter,
//   createSignalIfSupported,
//   parseAndCheckHttpResponse
// } = require('apollo-link-http-common')
// var { extractFiles, ReactNativeFile } = require('extract-files')

const _extracFiles = require('extract-files')
const extractFiles = _extracFiles.extracFiles
const ReactNativeFile = _extracFiles.ReactNativeFile
```
 Then cursor points at  the line `exports.createUploadLink = function createUploadLink ({` as below 
![5](https://user-images.githubusercontent.com/20510533/47788695-6c0fdf80-dd4d-11e8-9df7-f15e77925a6d.png)

So, I guess the ```ie 11``` cannot recognize the syntax like ```const { varA, varB } = require('module-name')```. But I am not clear about the problem of  function ```createUploadLink ```.

I hope these messages helpful.

**Comment by Leruiz** [comment]
And I use ```apollo-upload-client``` in a ```nuxt``` project. According to the build configurations, ```node modules``` will not be transpiled by ```babel``` at default. I added additional configurations to transpile ```apollo-upload-client``` in ```nuxt.config.js```, then the module can run normally.

**Comment by jaydenseric** [comment]
Thanks, those last clues were very helpful! I was able to work out that Babel is not working properly, I'll work on a fix.

**Comment by jaydenseric** [comment]
This should be fixed in [v9.1.0](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v9.1.0), please let me know how it goes 🤞

**Comment by Leruiz** [comment]
I have tested that ```v9.1.0``` has no problem. Now my web application can run normally in ie 11. Thanks a lot!

**Comment by jaydenseric** [comment]
Thanks for the report, and taking the time to investigate :)

**Comment by nathanschwarz** [comment]
Hello there, I still have issues with IE11 and also edge-legacy (tested on edge <= 18) with spread operators in `createUploadLink.js` : 
```
headers: {
        // Client awareness headers can be overridden by context `headers`.
        ...(name && { 'apollographql-client-name': name }),
        ...(version && { 'apollographql-client-version': version }),
        ...headers,
      },
```
In my final bundle the spread operators are not properly transformed in es5.
Thanks

**Comment by jaydenseric** [comment]
@nathanschwarz as documented in the readme and package `browserslist` field, the supported browsers match the [browserslist](https://npm.im/browserslist) query `> 0.5%, not OperaMini all, not IE > 0, not dead` — no version of IE (or legacy Edge) is supported:

- https://github.com/jaydenseric/apollo-upload-client/tree/v16.0.0#support
- https://github.com/jaydenseric/apollo-upload-client/blob/49fab25ed2e2fb3313df5785ce6a39e44c2987e4/package.json#L46

Here is the result of running `npx browserslist '> 0.5%, not OperaMini all, not IE > 0, not dead'`:

```
and_chr 96
and_uc 12.12
chrome 95
chrome 94
chrome 93
chrome 92
edge 95
edge 94
firefox 93
firefox 92
ios_saf 15
ios_saf 14.5-14.8
ios_saf 14.0-14.4
ios_saf 12.2-12.5
opera 79
safari 15
safari 14.1
safari 13.1
samsung 15.0
```

Note that `apollo-upload-client` no longer has any build step, so the browserslist query is just a way of defining user expectations and it also somewhat helps guide linting.
